/**
 * Temporal Graph API
 * API for Temporal Graph
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ji67mary@studserv.uni-leipzig.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type AggregationType = 'AverageDuration' | 'MaxDuration' | 'MaxTime' | 'MinDuration' | 'MinTime' | 'Count' | 'Max' | 'Min' | 'Sum' | 'None';

export const AggregationType = {
    AverageDuration: 'AverageDuration' as AggregationType,
    MaxDuration: 'MaxDuration' as AggregationType,
    MaxTime: 'MaxTime' as AggregationType,
    MinDuration: 'MinDuration' as AggregationType,
    MinTime: 'MinTime' as AggregationType,
    Count: 'Count' as AggregationType,
    Max: 'Max' as AggregationType,
    Min: 'Min' as AggregationType,
    Sum: 'Sum' as AggregationType,
    None: 'None' as AggregationType
};
