/**
 * Temporal Graph API
 * API for Temporal Graph
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ji67mary@studserv.uni-leipzig.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ChronoField = 'Nano_of_Second' | 'Nano_of_Day' | 'Micro_of_Second' | 'Micro_of_Day' | 'Milli_of_Second' | 'Milli_of_Day' | 'Second_of_Minute' | 'Second_of_Day' | 'Minute_of_Hour' | 'Minute_of_Day' | 'Hour_of_AMPM' | 'Hour_of_Day' | 'Clock_Hour_of_Day' | 'AMPM_of_Day' | 'Day_of_Week' | 'Aligned_Day_of_Week_in_Month' | 'Aligned_Day_of_Week_in_Year' | 'Day_of_Month' | 'Day_of_Year' | 'Epoch_Day' | 'Aligned_Week_of_Month' | 'Aligned_Week_of_Year' | 'Month_of_Year' | 'Proleptic_Month' | 'Year_of_Era' | 'Year' | 'Era' | 'Intant_Seconds' | 'Offset_Seconds';

export const ChronoField = {
    NanoOfSecond: 'Nano_of_Second' as ChronoField,
    NanoOfDay: 'Nano_of_Day' as ChronoField,
    MicroOfSecond: 'Micro_of_Second' as ChronoField,
    MicroOfDay: 'Micro_of_Day' as ChronoField,
    MilliOfSecond: 'Milli_of_Second' as ChronoField,
    MilliOfDay: 'Milli_of_Day' as ChronoField,
    SecondOfMinute: 'Second_of_Minute' as ChronoField,
    SecondOfDay: 'Second_of_Day' as ChronoField,
    MinuteOfHour: 'Minute_of_Hour' as ChronoField,
    MinuteOfDay: 'Minute_of_Day' as ChronoField,
    HourOfAMPM: 'Hour_of_AMPM' as ChronoField,
    HourOfDay: 'Hour_of_Day' as ChronoField,
    ClockHourOfDay: 'Clock_Hour_of_Day' as ChronoField,
    AMPMOfDay: 'AMPM_of_Day' as ChronoField,
    DayOfWeek: 'Day_of_Week' as ChronoField,
    AlignedDayOfWeekInMonth: 'Aligned_Day_of_Week_in_Month' as ChronoField,
    AlignedDayOfWeekInYear: 'Aligned_Day_of_Week_in_Year' as ChronoField,
    DayOfMonth: 'Day_of_Month' as ChronoField,
    DayOfYear: 'Day_of_Year' as ChronoField,
    EpochDay: 'Epoch_Day' as ChronoField,
    AlignedWeekOfMonth: 'Aligned_Week_of_Month' as ChronoField,
    AlignedWeekOfYear: 'Aligned_Week_of_Year' as ChronoField,
    MonthOfYear: 'Month_of_Year' as ChronoField,
    ProlepticMonth: 'Proleptic_Month' as ChronoField,
    YearOfEra: 'Year_of_Era' as ChronoField,
    Year: 'Year' as ChronoField,
    Era: 'Era' as ChronoField,
    IntantSeconds: 'Intant_Seconds' as ChronoField,
    OffsetSeconds: 'Offset_Seconds' as ChronoField
};
