/**
 * Temporal Graph API
 * API for Temporal Graph
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ji67mary@studserv.uni-leipzig.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ChronoUnit = 'CENTURIES' | 'DAYS' | 'DECADES' | 'ERAS' | 'FOREVER' | 'HALFDAYS' | 'HOURS' | 'MICROS' | 'MILLENIA' | 'MILLIS' | 'MINUTES' | 'MONTHS' | 'NANOS' | 'SECONDS' | 'WEEKS' | 'YEARS';

export const ChronoUnit = {
    CENTURIES: 'CENTURIES' as ChronoUnit,
    DAYS: 'DAYS' as ChronoUnit,
    DECADES: 'DECADES' as ChronoUnit,
    ERAS: 'ERAS' as ChronoUnit,
    FOREVER: 'FOREVER' as ChronoUnit,
    HALFDAYS: 'HALFDAYS' as ChronoUnit,
    HOURS: 'HOURS' as ChronoUnit,
    MICROS: 'MICROS' as ChronoUnit,
    MILLENIA: 'MILLENIA' as ChronoUnit,
    MILLIS: 'MILLIS' as ChronoUnit,
    MINUTES: 'MINUTES' as ChronoUnit,
    MONTHS: 'MONTHS' as ChronoUnit,
    NANOS: 'NANOS' as ChronoUnit,
    SECONDS: 'SECONDS' as ChronoUnit,
    WEEKS: 'WEEKS' as ChronoUnit,
    YEARS: 'YEARS' as ChronoUnit
};
