/**
 * Temporal Graph API
 * API for Temporal Graph
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ji67mary@studserv.uni-leipzig.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type GroupingType = 'Nothing' | 'Label' | 'Property' | 'Duration' | 'TimeInterval' | 'TimeStamp' | 'TimeStampField';

export const GroupingType = {
    Nothing: 'Nothing' as GroupingType,
    Label: 'Label' as GroupingType,
    Property: 'Property' as GroupingType,
    Duration: 'Duration' as GroupingType,
    TimeInterval: 'TimeInterval' as GroupingType,
    TimeStamp: 'TimeStamp' as GroupingType,
    TimeStampField: 'TimeStampField' as GroupingType
};
